### ISSUE TITLE
更新

### ISSUE THREAD

**Issue by lyekumchew** [akar1nchan/drrr-like-chat#2]
什么时候可以更新一下呢，增加一些新的功能，比如有人加入聊天室的时候可以播放铃声，查看聊天室的所有人，还有怎么删聊天室

**Comment by akar1nchan** [comment]
没时间

**Comment by lyekumchew** [comment]
那你可以告诉我手机没声音这个问题怎么解决？

**Comment by akar1nchan** [comment]
https://github.com/oddui/realtime_chat

**Comment by legendtang** [comment]
@lyekumchew 如果有兴趣的话，可以支持一下我的 Node.js 版本，https://github.com/legendtang/drrr-socketio-chat

房间功能还在筹备中

**Comment by lyekumchew** [comment]
@legendtang 当然支持，如果房间功能弄好了，记得一定叫我，如果有私聊功能那么再好不过了！！
